# Generated by Django 5.2 on 2025-05-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(unique=True)),
                ('name', models.TextField()),
                ('account', models.CharField(max_length=100)),
                ('campaign_group', models.CharField(max_length=100)),
                ('associated_entity', models.CharField(max_length=100)),
                ('objective_type', models.CharField(max_length=50)),
                ('cost_type', models.CharField(max_length=10)),
                ('pacing_strategy', models.CharField(max_length=50)),
                ('optimization_target_type', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('audience_expansion_enabled', models.BooleanField()),
                ('story_delivery_enabled', models.BooleanField()),
                ('offsite_delivery_enabled', models.BooleanField()),
                ('connected_television_only', models.BooleanField()),
                ('test', models.BooleanField()),
                ('serving_statuses', models.JSONField(default=list)),
                ('creative_selection', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLinkendin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OffsitePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iab_categories_exclude', models.JSONField(default=list)),
                ('publisher_include', models.JSONField(default=list)),
                ('publisher_exclude', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RunSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.JSONField()),
                ('exclude', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField()),
                ('changes', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_audit', to='api.auditstamp')),
                ('last_modified', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modified_audit', to='api.auditstamp')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='change_audit_stamps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.changeaudit'),
        ),
        migrations.CreateModel(
            name='CreativeLinkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='api.campaignlinkendin')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.creativelinkedin')),
            ],
        ),
        migrations.CreateModel(
            name='AdAnalyticsLinkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_analytics', to='api.creativelinkedin')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_budget', to='api.currencyamount'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unit_cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_cost', to='api.currencyamount'),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='api.creativelinkedin')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='locale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.locale'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offsite_preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.offsitepreferences'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='run_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.runschedule'),
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seniorities', to='api.creativelinkedin')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='targeting_criteria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.targetingcriteria'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.version'),
        ),
    ]
