# Generated by Django 5.2 on 2025-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creativelinkedin',
            name='creative_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creativelinkedin',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seniority',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seniority',
            name='seniority_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('country_id', 'creative')},
        ),
        migrations.AlterUniqueTogether(
            name='creativelinkedin',
            unique_together={('creative_id', 'campaign')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('title_id', 'creative')},
        ),
        migrations.AlterUniqueTogether(
            name='seniority',
            unique_together={('seniority_id', 'creative')},
        ),
    ]
