# Generated by Django 5.2 on 2025-05-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_country_country_id_alter_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCountRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_count_range', to='api.creativelinkedin')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='api.creativelinkedin')),
            ],
            options={
                'unique_together': {('industry_id', 'creative')},
            },
        ),
    ]
